coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "reach, diff, flags, components"
  behavior: default
  require_changes: false

github_checks:
  annotations: true
